[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "audiometry"
authors = [{name = "Liberty Hamilton", email = "libertyhamilton@gmail.com"}]
dynamic = ["version", "description"]
